[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
tessera-ui = "2"
tessera-ui-basic-components = "2"
tracing = "*"
tracing-subscriber = { version = "*", features = ["fmt", "env-filter"] }
