name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install rustfmt for nightly
        run: rustup component add rustfmt --toolchain nightly
      - name: Install stable
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Check all targets
        run: cargo +stable check --all-targets --verbose
      - name: Run tests
        run: cargo +stable test --verbose
      - name: Install rust-script
        run: cargo install rust-script
      - name: Check formatting
        run: cargo fmt --all -- --check && rust-script scripts/check-imports.rs .

  check_android:
    name: Check Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-linux-android
      - name: Install stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add aarch64-linux-android --toolchain stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-ndk
        run: cargo install cargo-ndk
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
      - name: Check Android target
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cargo +stable ndk -t arm64-v8a check -p tessera-ui --verbose
          cargo +stable ndk -t arm64-v8a check -p tessera-components --verbose
          cargo +stable ndk -t arm64-v8a check -p tessera-macros --verbose
          cargo +stable ndk -t arm64-v8a check -p tessera-shard --verbose
